package com.youngledo.jmcfx.domain.model;

public enum LiveMetricKind {
    HEAP_USED_PERCENT,
    HEAP_USED_BYTES,
    HEAP_COMMITTED_BYTES,
    HEAP_MAX_BYTES,
    NON_HEAP_USED_BYTES,
    NON_HEAP_COMMITTED_BYTES,
    THREAD_COUNT,
    PEAK_THREAD_COUNT,
    DAEMON_THREAD_COUNT,
    LOADED_CLASS_COUNT,
    TOTAL_LOADED_CLASS_COUNT,
    UNLOADED_CLASS_COUNT,
    PROCESS_CPU_LOAD_PERCENT,
    SYSTEM_CPU_LOAD_PERCENT,
    AVAILABLE_PROCESSORS,
    SYSTEM_LOAD_AVERAGE
}
