package io.github.youngledo.jmcfx.ui.jvm;

import io.github.youngledo.jmcfx.domain.model.ClassloadEvent;
import io.github.youngledo.jmcfx.domain.model.ClassloaderStatistics;
import io.github.youngledo.jmcfx.domain.model.ClassloaderSummary;
import io.github.youngledo.jmcfx.domain.model.CodeCacheStats;
import io.github.youngledo.jmcfx.domain.model.CodeCacheSweep;
import io.github.youngledo.jmcfx.domain.model.CompilationEvent;
import io.github.youngledo.jmcfx.domain.model.GcEvent;
import io.github.youngledo.jmcfx.domain.model.GcHeapSummary;
import io.github.youngledo.jmcfx.domain.model.GcReferenceStat;
import io.github.youngledo.jmcfx.domain.model.GcSummary;
import io.github.youngledo.jmcfx.domain.model.JvmFlag;
import io.github.youngledo.jmcfx.domain.model.JvmFlagChange;
import io.github.youngledo.jmcfx.domain.model.VmOperationEvent;
import io.github.youngledo.jmcfx.domain.model.VmOperationSummary;
import io.github.youngledo.jmcfx.ui.chart.TimelineChart;

import javafx.scene.control.Button;
import javafx.scene.control.Label;
import javafx.scene.control.TableView;

/// Narrow view handle for JVM Internals data table and timeline pages.
public record JvmInternalsPagesView(
        Label jvmInfoTitleLabel,
        Label jvmFlagsLabel,
        Label jvmFlagChangesLabel,
        TableView<JvmFlag> jvmFlagsTable,
        TableView<JvmFlagChange> jvmFlagChangesTable,
        Label gcConfigTitleLabel,
        Label gcConfigDescriptionLabel,
        Label gcSummaryTitleLabel,
        TableView<GcSummary> gcSummaryTable,
        Label gcDetailsTitleLabel,
        Label gcDetailsRecordingContextLabel,
        Button gcDetailsClearTimeRangeButton,
        TimelineChart gcHeapChart,
        TimelineChart gcMetaspaceChart,
        TimelineChart gcPauseChart,
        Label gcEventsLabel,
        TableView<GcEvent> gcEventsTable,
        Label gcReferenceStatsLabel,
        TableView<GcReferenceStat> gcReferenceStatsTable,
        Label gcHeapSummaryLabel,
        TableView<GcHeapSummary> gcHeapSummaryTable,
        Label compilationsTitleLabel,
        Label compilationsRecordingContextLabel,
        Button compilationsClearTimeRangeButton,
        TimelineChart compilationDurationChart,
        Label compilationEventsLabel,
        TableView<CompilationEvent> compilationsTable,
        Label compilationFailuresLabel,
        TableView<CompilationEvent> compilationFailuresTable,
        Label codeCacheTitleLabel,
        Label codeCacheRecordingContextLabel,
        Button codeCacheClearTimeRangeButton,
        TimelineChart codeCacheEntriesChart,
        TimelineChart codeCacheSweepChart,
        Label codeCacheSweepsLabel,
        TableView<CodeCacheSweep> codeCacheSweepsTable,
        Label codeCacheStatsLabel,
        TableView<CodeCacheStats> codeCacheStatsTable,
        Label classLoadingTitleLabel,
        Label classLoadingRecordingContextLabel,
        Button classLoadingClearTimeRangeButton,
        TimelineChart classLoadingChart,
        Label classLoadingHistogramLabel,
        TableView<ClassloaderSummary> classLoadingHistogramTable,
        Label classLoadingEventsLabel,
        TableView<ClassloadEvent> classLoadingEventsTable,
        Label classLoadingStatsLabel,
        TableView<ClassloaderStatistics> classLoadingStatsTable,
        Label vmOperationsTitleLabel,
        Button vmOperationsClearTimeRangeButton,
        Label vmOperationSummaryLabel,
        TableView<VmOperationSummary> vmOperationSummaryTable,
        Label vmOperationEventsLabel,
        TableView<VmOperationEvent> vmOperationEventsTable) {
}
