package com.youngledo.jmcfx.ui.shell;

import com.youngledo.jmcfx.domain.model.RecordingSummary;
import com.youngledo.jmcfx.ui.advanced.AdvancedJfrViewModel;
import com.youngledo.jmcfx.ui.environment.EnvironmentViewModel;
import com.youngledo.jmcfx.ui.events.EventBrowserViewModel;
import com.youngledo.jmcfx.ui.exceptions.ExceptionViewModel;
import com.youngledo.jmcfx.ui.fileio.FileIOViewModel;
import com.youngledo.jmcfx.ui.gc.G1GcViewModel;
import com.youngledo.jmcfx.ui.heap.HeapViewModel;
import com.youngledo.jmcfx.ui.javaapp.JavaAppOverviewViewModel;
import com.youngledo.jmcfx.ui.javaapp.NativeLibraryViewModel;
import com.youngledo.jmcfx.ui.javaapp.SecurityViewModel;
import com.youngledo.jmcfx.ui.javaapp.ThreadDumpViewModel;
import com.youngledo.jmcfx.ui.jfx.JavaFxEventsViewModel;
import com.youngledo.jmcfx.ui.jvm.ClassLoadingViewModel;
import com.youngledo.jmcfx.ui.jvm.CodeCacheViewModel;
import com.youngledo.jmcfx.ui.jvm.CompilationsViewModel;
import com.youngledo.jmcfx.ui.jvm.GcConfigViewModel;
import com.youngledo.jmcfx.ui.jvm.GcDetailsViewModel;
import com.youngledo.jmcfx.ui.jvm.GcSummaryViewModel;
import com.youngledo.jmcfx.ui.jvm.JvmInfoViewModel;
import com.youngledo.jmcfx.ui.jvm.VmOperationsViewModel;
import com.youngledo.jmcfx.ui.leaks.LeakSuspectsViewModel;
import com.youngledo.jmcfx.ui.locks.LockViewModel;
import com.youngledo.jmcfx.ui.metadata.JfrMetadataViewModel;
import com.youngledo.jmcfx.ui.overview.OverviewViewModel;
import com.youngledo.jmcfx.ui.profiling.ProfilingViewModel;
import com.youngledo.jmcfx.ui.rules.RuleResultsViewModel;
import com.youngledo.jmcfx.ui.socketio.SocketIOViewModel;
import com.youngledo.jmcfx.ui.threads.ThreadViewModel;
import com.youngledo.jmcfx.ui.tlab.TlabViewModel;

record PreparedRecordingWorkspace(
        RecordingSummary recording,
        OverviewViewModel overview,
        EventBrowserViewModel events,
        RuleResultsViewModel analysis,
        ProfilingViewModel profiling,
        ExceptionViewModel exceptions,
        ThreadViewModel threads,
        FileIOViewModel fileio,
        SocketIOViewModel socketio,
        LockViewModel locks,
        HeapViewModel heap,
        LeakSuspectsViewModel leakSuspects,
        TlabViewModel tlab,
        JvmInfoViewModel jvmInfo,
        GcConfigViewModel gcConfig,
        GcSummaryViewModel gcSummary,
        GcDetailsViewModel gcDetails,
        CompilationsViewModel compilations,
        CodeCacheViewModel codeCache,
        ClassLoadingViewModel classLoading,
        VmOperationsViewModel vmOperations,
        EnvironmentViewModel environment,
        JavaAppOverviewViewModel javaAppOverview,
        SecurityViewModel security,
        NativeLibraryViewModel nativeLibraries,
        ThreadDumpViewModel threadDumps,
        JfrMetadataViewModel metadata,
        G1GcViewModel g1Gc,
        JavaFxEventsViewModel javaFxEvents,
        AdvancedJfrViewModel advancedJfr) {
}
