<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.1.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.1.0 https://maven.apache.org/xsd/maven-4.1.0.xsd">
    <modelVersion>4.1.0</modelVersion>
    <parent/>
    <artifactId>jmc-fx-app</artifactId>
    <name>JMC FX Application</name>
    <dependencies>
        <dependency>
            <groupId>com.youngledo.jmcfx</groupId>
            <artifactId>jmc-fx-ui</artifactId>
        </dependency>
        <dependency>
            <groupId>com.youngledo.jmcfx</groupId>
            <artifactId>jmc-fx-adapter-jmc</artifactId>
        </dependency>
    </dependencies>
    <build>
        <plugins>
            <plugin>
                <groupId>org.openjfx</groupId>
                <artifactId>javafx-maven-plugin</artifactId>
                <configuration>
                    <skip>false</skip>
                    <mainClass>com.youngledo.jmcfx.app.JmcFxApplication</mainClass>
                </configuration>
            </plugin>
        </plugins>
    </build>
</project>
